# Reactant support matrix: what compiles and differentiates under Reactant
# today. Not part of `Pkg.test`; run with `task test-reactant` (Julia 1.12).
#
# Each case, mode, configuration and backend runs in its own subprocess with
# a timeout, so one hang does not stall the rest. Results go to RESULTS.md
# beside this file. `@test` covers the entries `expected.jl` marks as working
# and `@test_broken` the rest, so a newly working entry shows as an
# unexpected pass. GPU entries are skipped when Reactant finds no GPU.
#
# Environment variables:
#   REACTANT_TIMEOUT   seconds per subprocess (default 300)
#   REACTANT_CASES     comma-separated case names (default all)
#   REACTANT_CONFIGS   comma-separated configs (default "extension")
#   REACTANT_BACKENDS  comma-separated backends (default "cpu,gpu")
#   REACTANT_REUSE     "1" rebuilds RESULTS.md and the tests from results.tsv
using Test, Dates, Printf
import Pkg

include(joinpath(@__DIR__, "cases.jl"))
using .ReactantCases
include(joinpath(@__DIR__, "expected.jl"))

envlist(key, default) = split(get(ENV, key, default), ',')
const TIMEOUT = parse(Float64, get(ENV, "REACTANT_TIMEOUT", "300"))
const NAMES = let s = get(ENV, "REACTANT_CASES", "")
    isempty(s) ? [c.name for c in CASES] : split(s, ',')
end
const CONFIGS = envlist("REACTANT_CONFIGS", "extension")
const BACKENDS = envlist("REACTANT_BACKENDS", "cpu,gpu")
const MODES = ("forward", "reverse")
const FIELDS = (
    :status, :relerr, :compile_s, :run_us, :plain_us, :error, :frame,
    :message,
)

padfields(v, n, x) = vcat(v, fill(x, max(0, n - length(v))))
blank_result() = NamedTuple{FIELDS}(ntuple(_ -> "", length(FIELDS)))

# The last lines of a log, for a subprocess that died without a result.
function log_tail(log)
    isfile(log) || return ""
    lines = filter(!isempty, readlines(log))
    return replace(join(last(lines, 3), " "), r"[\t|]+" => " ")
end

function run_probe(name, mode, config, backend, dir)
    stem = joinpath(dir, "$name-$mode-$config-$backend")
    out, log = "$stem.tsv", "$stem.log"
    cmd = `$(Base.julia_cmd()) --project=$(@__DIR__) --startup-file=no
        $(joinpath(@__DIR__, "probe.jl")) $name $mode $config $backend $out`
    t0 = time()
    p = run(pipeline(cmd; stdout = log, stderr = log); wait = false)
    timedout = timedwait(() -> process_exited(p), TIMEOUT; pollint = 1.0) ===
        :timed_out
    if timedout
        kill(p, Base.SIGKILL)
        wait(p)
    end
    wall = time() - t0
    r = if timedout
        merge(
            blank_result(), (;
                status = "timeout", error = "Timeout",
                message = "no result after $(Int(TIMEOUT)) s",
            )
        )
    elseif isfile(out)
        fields = padfields(split(readchomp(out), '\t'), length(FIELDS), "")
        NamedTuple{FIELDS}(Tuple(fields))
    else
        merge(
            blank_result(), (;
                status = "error", error = "Crash",
                message = first("exit code $(p.exitcode): " * log_tail(log), 300),
            )
        )
    end
    @printf(
        "%-24s %-8s %-9s %-4s %-8s %5.0f s  %s %s\n",
        name, mode, config, backend, r.status, wall, r.error, r.frame
    )
    flush(stdout)
    return merge(r, (; name, mode, config, backend, wall))
end

function versions()
    deps = Pkg.dependencies()
    v(name) = string(only(d.version for d in values(deps) if d.name == name))
    return (; Reactant = v("Reactant"), Enzyme = v("Enzyme"))
end

function cell(r)
    r === nothing && return "not run"
    r.status == "works" &&
        return "works ($(r.compile_s) s / $(r.run_us) µs)"
    r.status == "wrong" && return "wrong (relerr $(r.relerr))"
    r.status in ("timeout", "skipped") && return r.status
    return r.frame in ("", "-") ? "error: $(r.error)" :
        "error: $(r.error) in `$(r.frame)`"
end

function write_results(path, results, elapsed)
    function find(n, m, c, b)
        i = findfirst(
            r -> (r.name, r.mode, r.config, r.backend) == (n, m, c, b),
            results
        )
        return i === nothing ? nothing : results[i]
    end
    vs = versions()
    cols = [(m, b) for b in ("cpu", "gpu") for m in MODES]
    io = IOBuffer()
    println(io, "# Reactant support\n")
    println(io, "Generated by `test/reactant/runtests.jl` (`task test-reactant`); do not edit by hand.")
    println(io, "Run on $(Dates.today()), Julia $(VERSION), Reactant $(vs.Reactant), Enzyme $(vs.Enzyme).")
    println(io, "Sizes: T = $(ReactantCases.T) steps, L = $(ReactantCases.L) lags, S = $(ReactantCases.S) strata.")
    println(io, "Total run time $(round(elapsed / 60; digits = 1)) min, one subprocess per cell, timeout $(Int(TIMEOUT)) s.\n")
    println(io, "- `extension`: the package as it is on this commit, with its Reactant extension (`ext/ComposableRecurrencesReactantExt.jl`).")
    println(io, "- `forward`: `Reactant.@compile` of the operator call against plain Julia.")
    println(io, "- `reverse`: `Enzyme.gradient` inside `@compile` of a weighted sum of the output, against ForwardDiff.")
    println(io, "- `works` cells give compile time (s) / median run time (µs); `wrong` means relative error ≥ 1e-8.")
    println(io, "- The control row's compile time is Reactant's fixed first-compile cost, included in every cell.")
    for config in CONFIGS
        println(io, "\n## $config\n")
        println(io, "| Case | Forward CPU | Reverse CPU | Forward GPU | Reverse GPU |")
        println(io, "|---|---|---|---|---|")
        for c in CASES
            c.name in NAMES || continue
            cells = [cell(find(c.name, m, config, b)) for (m, b) in cols]
            println(io, "| ", c.description, " | ", join(cells, " | "), " |")
        end
    end
    println(io, "\n## Details\n")
    println(io, "Plain Julia is the operator call (forward) or `ForwardDiff.gradient` (reverse), on the CPU.\n")
    println(io, "| Case | Mode | Config | Backend | Status | Rel. error | Compile (s) | Run (µs) | Plain Julia (µs) | Where | Message |")
    println(io, "|---|---|---|---|---|---|---|---|---|---|---|")
    for r in results
        row = (
            r.name, r.mode, r.config, r.backend, r.status, r.relerr,
            r.compile_s, r.run_us, r.plain_us, r.frame, first(r.message, 160),
        )
        println(io, "| ", join(row, " | "), " |")
    end
    println(io)
    print(io, read(joinpath(@__DIR__, "extension.md"), String))
    write(path, String(take!(io)))
    return path
end

const KEYS = (FIELDS..., :name, :mode, :config, :backend, :wall)

# Raw results, one row per cell, so the tests and RESULTS.md can be
# rebuilt without rerunning (`REACTANT_REUSE=1`).
function write_raw(path, results, elapsed)
    open(path, "w") do io
        println(io, "# elapsed_s\t", elapsed)
        println(io, join(KEYS, '\t'))
        for r in results
            println(io, join((getfield(r, k) for k in KEYS), '\t'))
        end
    end
    return path
end
function read_raw(path)
    lines = readlines(path)
    elapsed = parse(Float64, split(lines[1], '\t')[2])
    rows = map(lines[3:end]) do l
        v = padfields(split(l, '\t'), length(KEYS), "")
        NamedTuple{KEYS}(Tuple(v))
    end
    return rows, elapsed
end

const RAW = joinpath(@__DIR__, "results.tsv")
if get(ENV, "REACTANT_REUSE", "") == "1"
    results, elapsed = read_raw(RAW)
else
    results = NamedTuple[]
    elapsed = @elapsed mktempdir() do dir
        for config in CONFIGS, backend in BACKENDS, name in NAMES, mode in MODES
            push!(results, run_probe(name, mode, config, backend, dir))
        end
    end
    write_raw(RAW, results, elapsed)
end
write_results(joinpath(@__DIR__, "RESULTS.md"), results, elapsed)
@printf("Total %.1f min\n", elapsed / 60)

@testset "Reactant support" begin
    @testset "extension loads without ambiguities" begin
        cmd = `$(Base.julia_cmd()) --project=$(@__DIR__) --startup-file=no
            $(joinpath(@__DIR__, "extension_check.jl"))`
        @test success(pipeline(cmd; stdout, stderr))
    end
    for config in CONFIGS, backend in BACKENDS
        @testset "$config $backend" begin
            for r in results
                (r.config, r.backend) == (config, backend) || continue
                @testset "$(r.name) $(r.mode)" begin
                    key = (r.name, r.mode, config, backend)
                    if r.status == "skipped"
                        @test_skip r.status == "works"
                    elseif get(EXPECTED, key, false)
                        @test r.status == "works"
                    else
                        # The error class is in expected.jl and RESULTS.md.
                        @test_broken r.status == "works"
                    end
                end
            end
        end
    end
end
