# Seeded EpiBranch.jl `HomogeneousProcess` simulations with a protected
# pool, for the vaccination use-case test.
#
# Source: https://github.com/epiforecasts/EpiBranch.jl at commit
# 2b1fdbaf, generated by `epibranch_homogeneous_generate.jl`.
# Each arm runs seeds 1:N_RUNS with StableRNG. Attack rates count
# index cases and are means over major outbreaks, with standard errors.
# Do not edit by hand.
module EpiBranchHomogeneousReference

const N = 5000
const R0 = 2.0
const INFECTIOUS_PERIOD = 4.0
const N_INITIAL = 10
const COVERAGE = 0.4
const EFFICACY = 0.7
const N_RUNS = 200
const MAJOR = 0.1

const NONE = (n_major = 200, total = (mean = 0.7978290000000001, se = 0.0009190539132593836), unvaccinated = (mean = 0.7984292643111158, se = 0.0009990010090806228), vaccinated = (mean = 0.7969358216460095, se = 0.0010093193399510838))
const ALL_OR_NOTHING = (n_major = 195, total = (mean = 0.3909025641025641, se = 0.0020913670766948543), unvaccinated = (mean = 0.542233636164333, se = 0.0028222795256090706), vaccinated = (mean = 0.1646966287195176, se = 0.001010884349584579))
const LEAKY = (n_major = 197, total = (mean = 0.45441015228426396, se = 0.002151004933407341), unvaccinated = (mean = 0.597669544657621, se = 0.0025323488190413107), vaccinated = (mean = 0.23993558202126197, se = 0.001617551482637883))

end
