# Generates `epibranch.jl`, the EpiBranch.jl reference values for the
# probability generating function (PGF) use-case tests. Run once, in a
# throwaway environment, not as part of the test suite:
#
#     julia epibranch_generate.jl > epibranch.jl
#
# The script installs EpiBranch.jl at the pinned commit below into a
# temporary environment. The tests read the printed constants only, so
# EpiBranch.jl is not a test dependency.
using Pkg
Pkg.activate(; temp = true)
const COMMIT = "2b1fdbaf9d638c5bd5ccd809a0a6b882949fc957"  # pragma: allowlist secret
Pkg.add(; url = "https://github.com/epiforecasts/EpiBranch.jl", rev = COMMIT, io = devnull)
Pkg.add("Distributions"; io = devnull)
using EpiBranch, Distributions

const EB = EpiBranch
const MAXLEN = 20

# Log-likelihood of each single chain length 0:MAXLEN, which gives the whole
# chain-length pmf, and of one multi-point dataset.
single_ll(offspring) = [
    EB.loglikelihood(EB.ChainLengths([len]), offspring) for len in 0:MAXLEN
]
const DATA = [0, 1, 1, 2, 3, 5, 0, 8]
data_ll(offspring) = EB.loglikelihood(EB.ChainLengths(DATA), offspring)

# Negative binomial offspring. EpiBranch recomputes `p = k / (k + mean)`
# before iterating, so that is the `p` recorded.
nb_k, nb_R = 0.5, 0.8
nb = NegativeBinomial(nb_k, nb_k / (nb_k + nb_R))
nb_p = nb.r / (nb.r + mean(nb))

# Poisson offspring.
pois = Poisson(0.7)
pois_λ = mean(pois)

# Containment with individual and population control: EpiBranch iterates
# `q = c + (1 - c) G(q)` with the offspring law at the effective R.
contain = (; R = 2.5, k = 0.3, ind_control = 0.2, pop_control = 0.1, n_initial = 3)
contain_law = NegativeBinomial(
    contain.k,
    contain.k / (contain.k + (1 - contain.pop_control) * contain.R)
)
contain_value = EB.probability_contain(
    contain.R, contain.k; contain.ind_control, contain.pop_control,
    contain.n_initial
)

# Extinction, NegBin(R, k) and Poisson.
ext = (; R = 2.0, k = 0.5)
ext_law = NegativeBinomial(ext.k, ext.k / (ext.k + ext.R))
ext_value = EB.extinction_probability(ext.R, ext.k)
ext_pois = Poisson(1.8)
ext_pois_value = EB.extinction_probability(ext_pois)

# Multi-type extinction, strongly connected and supercritical.
mt_M = [1.5 0.6; 0.4 1.2]
mt_k = 0.5
mt = EB.MultiTypeOffspring(mt_M, R -> NegativeBinomial(mt_k, mt_k / (mt_k + R)))
mt_laws = [mt.dist_fn(R) for R in mt.R_by_type]
mt_value = EB.extinction_probability(mt)

p(name, x) = println("const ", name, " = ", repr(x))
println("# EpiBranch.jl reference values for the PGF use-case tests.")
println("#")
println("# Source: https://github.com/epiforecasts/EpiBranch.jl at commit")
println("# ", COMMIT[1:8], ", generated by `epibranch_generate.jl`. Values are")
println("# printed at full precision; do not edit by hand.")
println("module EpiBranchReference")
println()
println("# Chain-length log-likelihoods, `loglikelihood(ChainLengths(data), offspring)`.")
p("MAXLEN", MAXLEN)
p("DATA", DATA)
p("NB_K", nb_k)
p("NB_P", nb_p)
p("NB_SINGLE_LL", single_ll(nb))
p("NB_DATA_LL", data_ll(nb))
p("POIS_LAMBDA", pois_λ)
p("POIS_SINGLE_LL", single_ll(pois))
p("POIS_DATA_LL", data_ll(pois))
println()
println("# probability_contain(R, k; ind_control, pop_control, n_initial).")
p("CONTAIN", contain)
p("CONTAIN_RP", params(contain_law))
p("CONTAIN_VALUE", contain_value)
println()
println("# extinction_probability(R, k) and extinction_probability(Poisson(λ)).")
p("EXT", ext)
p("EXT_RP", params(ext_law))
p("EXT_VALUE", ext_value)
p("EXT_POIS_LAMBDA", mean(ext_pois))
p("EXT_POIS_VALUE", ext_pois_value)
println()
println("# Multi-type extinction_probability(MultiTypeOffspring(M, R -> NegBin)).")
p("MT_M", mt_M)
p("MT_ALLOC", mt.alloc_probs)
p("MT_NB_R", [params(l)[1] for l in mt_laws])
p("MT_NB_P", [params(l)[2] for l in mt_laws])
p("MT_VALUE", mt_value)
println()
println("end")
