# Seeded EpiBranch.jl `BranchingProcess` simulations of the mean
# offspring of an index case under isolation, for the isolation
# use-case test.
#
# Source: https://github.com/epiforecasts/EpiBranch.jl at commit
# 44407737, generated by `epibranch_isolation_generate.jl`.
# Each arm runs N_RUNS index cases from StableRNG(1). Do not edit by
# hand.
module EpiBranchIsolationReference

const R = 2.0
const GEN_SHAPE = 2
const GEN_SCALE = 3.0
const INC_SHAPE = 2
const INC_SCALE = 2.0
const DELAY_SCALE = 2.0
const PROB_ASYMPTOMATIC = 0.2
const TEST_SENSITIVITY = 0.75
const POST_ISOLATION_TRANSMISSION = 0.1
const N_RUNS = 40000

const NONE = (mean = 2.001225, se = 0.007038595458614294)
const ISOLATION = (mean = 1.48555, se = 0.006672959849072125)

end
