# Generates `epibranch_isolation.jl`, seeded EpiBranch.jl `BranchingProcess`
# simulations of the mean offspring of an index case under isolation, for
# the isolation use-case test. Run once, in a throwaway environment, not as
# part of the test suite:
#
#     julia epibranch_isolation_generate.jl > epibranch_isolation.jl
#
# The script installs EpiBranch.jl at the pinned commit below into a
# temporary environment. The tests read the printed constants only, so
# EpiBranch.jl is not a test dependency.
#
# Each index case has Poisson(R) contacts at generation times drawn from
# Gamma(GEN_SHAPE, GEN_SCALE). A share 1 - PROB_ASYMPTOMATIC develop symptoms
# after an incubation period drawn from Gamma(INC_SHAPE, INC_SCALE); of these
# a share TEST_SENSITIVITY isolate after a further Exponential(DELAY_SCALE)
# delay. Isolation lasts for good and blocks a contact after it with
# probability 1 - POST_ISOLATION_TRANSMISSION. The generation time is drawn
# independently of the incubation period. The shapes are integers, so the
# infection-to-isolation delay is Gamma(INC_SHAPE + 1, INC_SCALE) when
# DELAY_SCALE == INC_SCALE.
using Pkg
Pkg.activate(; temp = true)
const COMMIT = "444077377957029e004380ca87f69df76aacb1bb"  # pragma: allowlist secret
Pkg.add(; url = "https://github.com/epiforecasts/EpiBranch.jl", rev = COMMIT, io = devnull)
Pkg.add(["Distributions", "StableRNGs"]; io = devnull)
using EpiBranch, Distributions, StableRNGs
using Statistics: mean, std

const R = 2.0
const GEN_SHAPE, GEN_SCALE = 2, 3.0
const INC_SHAPE, INC_SCALE = 2, 2.0
const DELAY_SCALE = 2.0
const PROB_ASYMPTOMATIC = 0.2
const TEST_SENSITIVITY = 0.75
const POST_ISOLATION_TRANSMISSION = 0.1
const N_RUNS = 40_000

function model(interventions)
    return ModelSpec(
        BranchingProcess(Poisson(R), Gamma(GEN_SHAPE, GEN_SCALE));
        interventions,
        attributes = clinical_presentation(;
            incubation_period = Gamma(INC_SHAPE, INC_SCALE),
            prob_asymptomatic = PROB_ASYMPTOMATIC
        )
    )
end

isolation = Isolation(;
    onset_to_isolation_delay = Exponential(DELAY_SCALE), duration = Inf,
    test_sensitivity = TEST_SENSITIVITY,
    post_isolation_transmission = POST_ISOLATION_TRANSMISSION
)

# Infected offspring of each run's single index case, as a mean with its
# standard error. Two generations are simulated so that every transmission
# from the index case is resolved.
function offspring(interventions)
    states = simulate(
        model(interventions), N_RUNS; max_generations = 2, rng = StableRNG(1)
    )
    n = [
        count(i -> i.generation == 1 && is_infected(i), s.individuals)
            for s in states
    ]
    return (; mean = mean(n), se = std(n) / sqrt(N_RUNS))
end

p(name, x) = println("const ", name, " = ", repr(x))
println("# Seeded EpiBranch.jl `BranchingProcess` simulations of the mean")
println("# offspring of an index case under isolation, for the isolation")
println("# use-case test.")
println("#")
println("# Source: https://github.com/epiforecasts/EpiBranch.jl at commit")
println("# ", COMMIT[1:8], ", generated by `epibranch_isolation_generate.jl`.")
println("# Each arm runs N_RUNS index cases from StableRNG(1). Do not edit by")
println("# hand.")
println("module EpiBranchIsolationReference")
println()
p("R", R)
p("GEN_SHAPE", GEN_SHAPE)
p("GEN_SCALE", GEN_SCALE)
p("INC_SHAPE", INC_SHAPE)
p("INC_SCALE", INC_SCALE)
p("DELAY_SCALE", DELAY_SCALE)
p("PROB_ASYMPTOMATIC", PROB_ASYMPTOMATIC)
p("TEST_SENSITIVITY", TEST_SENSITIVITY)
p("POST_ISOLATION_TRANSMISSION", POST_ISOLATION_TRANSMISSION)
p("N_RUNS", N_RUNS)
println()
p("NONE", offspring([]))
p("ISOLATION", offspring([isolation]))
println()
println("end")
