# Generates `epibranch_homogeneous.jl`, seeded EpiBranch.jl
# `HomogeneousProcess` simulations of a population with a protected pool
# for the vaccination use-case test. Run once, in a throwaway environment,
# not as part of the test suite:
#
#     julia epibranch_homogeneous_generate.jl > epibranch_homogeneous.jl
#
# The script installs EpiBranch.jl at the pinned commit below into a
# temporary environment. The tests read the printed constants only, so
# EpiBranch.jl is not a test dependency.
#
# `HomogeneousProcess` simulates a stochastic SIR model in continuous time
# by the Sellke threshold construction. It does not apply a dose rollout
# (`MassVaccination`), so the protected pool is set before the outbreak
# through each person's `susceptibility`, which scales the force of
# infection they feel. A share `COVERAGE` of the population is vaccinated:
#
#   all-or-nothing: a share `EFFICACY` of those vaccinated respond and get
#                   susceptibility 0; the others keep susceptibility 1;
#   leaky:          everyone vaccinated gets susceptibility 1 - `EFFICACY`.
using Pkg
Pkg.activate(; temp = true)
const COMMIT = "2b1fdbaf9d638c5bd5ccd809a0a6b882949fc957"  # pragma: allowlist secret
Pkg.add(; url = "https://github.com/epiforecasts/EpiBranch.jl", rev = COMMIT, io = devnull)
Pkg.add(["Distributions", "StableRNGs"]; io = devnull)
using EpiBranch, Distributions, StableRNGs
using Statistics: mean, std

const N = 5_000
const R0 = 2.0
const INFECTIOUS_PERIOD = 4.0
const N_INITIAL = 10
const COVERAGE = 0.4
const EFFICACY = 0.7
const N_RUNS = 200
# Runs that infect fewer than this share of the population are minor
# outbreaks that died out early; the deterministic model describes the
# major outbreak, so they are counted and left out of the means.
const MAJOR = 0.1

function attributes(arm)
    return function (rng, ind)
        vaccinated = rand(rng) < COVERAGE
        ind.state[:vaccinated] = vaccinated
        ind.susceptibility = if !vaccinated || arm === :none
            1.0
        elseif arm === :all_or_nothing
            rand(rng) < EFFICACY ? 0.0 : 1.0
        else
            1.0 - EFFICACY
        end
        return nothing
    end
end

function model(arm)
    return ModelSpec(
        HomogeneousProcess(;
            transmission_rate = R0 / INFECTIOUS_PERIOD, population_size = N
        );
        progression = [
            Transition(
                :recovered; from = :infection,
                delay = Exponential(INFECTIOUS_PERIOD), terminal = true
            ),
        ],
        attributes = attributes(arm)
    )
end

# Share of the unvaccinated and vaccinated people infected in one run,
# index cases included, and the number of vaccinated people.
function run(arm, seed)
    state = simulate(model(arm); n_initial = N_INITIAL, rng = StableRNG(seed))
    inds = state.individuals
    vac = [ind.state[:vaccinated] for ind in inds]
    inf = [is_infected(ind) for ind in inds]
    return (;
        total = count(inf) / N,
        unvaccinated = count(inf .& .!vac) / count(.!vac),
        vaccinated = count(inf .& vac) / count(vac),
    )
end

function summarise(arm)
    runs = [run(arm, seed) for seed in 1:N_RUNS]
    major = filter(r -> r.total >= MAJOR, runs)
    stat(f) = (; mean = mean(f.(major)), se = std(f.(major)) / sqrt(length(major)))
    return (;
        n_major = length(major),
        total = stat(r -> r.total),
        unvaccinated = stat(r -> r.unvaccinated),
        vaccinated = stat(r -> r.vaccinated),
    )
end

p(name, x) = println("const ", name, " = ", repr(x))
println("# Seeded EpiBranch.jl `HomogeneousProcess` simulations with a protected")
println("# pool, for the vaccination use-case test.")
println("#")
println("# Source: https://github.com/epiforecasts/EpiBranch.jl at commit")
println("# ", COMMIT[1:8], ", generated by `epibranch_homogeneous_generate.jl`.")
println("# Each arm runs seeds 1:N_RUNS with StableRNG. Attack rates count")
println("# index cases and are means over major outbreaks, with standard errors.")
println("# Do not edit by hand.")
println("module EpiBranchHomogeneousReference")
println()
p("N", N)
p("R0", R0)
p("INFECTIOUS_PERIOD", INFECTIOUS_PERIOD)
p("N_INITIAL", N_INITIAL)
p("COVERAGE", COVERAGE)
p("EFFICACY", EFFICACY)
p("N_RUNS", N_RUNS)
p("MAJOR", MAJOR)
println()
p("NONE", summarise(:none))
p("ALL_OR_NOTHING", summarise(:all_or_nothing))
p("LEAKY", summarise(:leaky))
println()
println("end")
